2nd run results

diff --git a/.github/workflows/test-apps.yml b/.github/workflows/test-apps.yml
--- a/.github/workflows/test-apps.yml
+++ b/.github/workflows/test-apps.yml
@@ -709,12 +709,13 @@ jobs:
             fi
             rm -f "$KoFile"
           done
+          rm -f results/failing
 
       - name: "Upload KO Results ☝️"
         if: failure()
         uses: actions/upload-artifact@v4
         with:
-          path: programs/x86_64/results/ko-*
+          path: results/ko-*
           if-no-files-found: warn
           retention-days: 1
           compression-level: 0
@@ -723,7 +724,7 @@ jobs:
         if: failure()
         uses: actions/upload-artifact@v4
         with:
-          path: programs/x86_64/results/failed
+          path: results/failed
           if-no-files-found: warn
           retention-days: 1
           compression-level: 0
@@ -732,7 +733,7 @@ jobs:
         # if: success()
         uses: actions/upload-artifact@v4
         with:
-          path: programs/x86_64/results/ok-*
+          path: results/ok-*
           if-no-files-found: ignore
           retention-days: 1
           compression-level: 0
@@ -740,7 +741,7 @@ jobs:
       - name: "Upload out ⬆️"
         uses: actions/upload-artifact@v4
         with:
-          path: programs/x86_64/results/out-*
+          path: results/out-*
           if-no-files-found: warn
           retention-days: 1
           compression-level: 0
@@ -750,7 +751,7 @@ jobs:
 
       - name: commit
         run: |
-          rm -f failing || echo "Removing failing failed"
+          rm -f results/failing || echo "Removing failing"
           if [ -f results/excluded ]; then
             sort -u results/excluded -o results/excluded  || echo "Sorting failed"
             git add results/excluded || echo "Excluded not added"
